name: Compile

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  node14:
    name: node v14 - tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: snyk install
        run: npm i -g snyk
      - name: install
        run: npm install
      - name: dependencies
        run: npm ci
      - name: settings
        run: cp settings.example.json settings.json
      - name: tsc
        uses: icrawl/action-tsc@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          job-name: tsc
