name: Compile

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  node18:
    name: node v18 - tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: dependencies
        run: npm ci
      - name: settings
        run: cp settings.example.json settings.json
      - name: tsc
        uses: icrawl/action-tsc@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
