name: Deploy
on:
    push:
        tags:
            - "v*-Release"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Configure Docker Daemon
              run: |
                  sudo mkdir -p /etc/docker
                  echo '{ "max-concurrent-uploads": 1, "max-single-upload-size": 52428800 }' | sudo tee /etc/docker/daemon.json
                  sudo systemctl restart docker
            - name: Print Docker Configuration
              run: cat /etc/docker/daemon.json
            - name: Login
              run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login ${{secrets.DOCKER_URL}} -u admin --password-stdin
            - name: Build
              run: docker build -t ${{ secrets.DOCKER_URL }}/del/site:${GITHUB_REF#refs/tags/} .
            - name: Push
              run: docker push ${{ secrets.DOCKER_URL }}/del/site:${GITHUB_REF#refs/tags/}
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Login
              run: |
                  mkdir ~/.kube
                  echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
            - name: Set image
              run: kubectl set image deployment/site site=${{ secrets.DOCKER_URL }}/del/site:${GITHUB_REF#refs/tags/}
            - name: Rollout status
              run: kubectl rollout status deployment/site
